services:
  app:
    image: ${DOCKERHUB_USERNAME:-hariketan03}/rv-lms:latest
    container_name: rv-lms-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
    ports:
      - "3005:3000"
    volumes:
      - uploads:/app/public/uploads
    networks:
      - app_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  app_network:
    driver: bridge

volumes:
  uploads:
